import { Button, Palette } from "std-widgets.slint";
import { Sidebar } from "sidebar.slint";
import {
    SlintEventRow,
    SlintCompetitorRow,
    SlintRaceEvent,
    SlintSkaterTime,
} from "structs.slint";
import { MainSection } from "mainsection.slint";
import { SettingsData, SettingsMenu } from "settings.slint";

export component MainWindow inherits Window {
    resize-border-width: 2px;
    property <float> split: 20%;
    property <bool> slider_hovered: false;
    property <bool> resizing: false;
    property <bool> settings_shown;

    out property <int> selected_lif_file: -1;

    in property <bool> race_event_set: false;
    in property <SlintRaceEvent> full_event;
    in property <SlintEventRow> event;
    in property <[[StandardListViewItem]]> table_data;
    in property <[string]> lif_files;

    in-out property <SettingsData> settings_data;

    in property <[image]> pdf_images;
    out property <float> pdf_image_width;

    out property <int> table_sort_index: main_section.table_sort_index;
    out property <bool> table_sort_ascending: main_section.table_sort_ascending;
    out property <string> lif_file_filter;

    in property <int> tab_index: 0;

    callback genpdf_button_clicked();
    callback print_button_clicked();

    callback table_changed();
    callback filter_changed();

    callback settings_add_path();
    callback settings_remove_path(int);
    callback settings_edit_path(int, string);
    callback general_settings_update(SettingsData);
    callback settings_button_clicked();
    callback settings_close_button_clicked();

    // Slider touch area
    TouchArea {
        width: parent.width;
        height: parent.height;
        pointer-event(event) => {
            if (event.kind == PointerEventKind.up) {
                resizing = false;
            }
            if (abs(self.mouse-x - (parent.width * split)) >= 4px) {
                slider_hovered = false;
                self.mouse-cursor = MouseCursor.default;
            } else {
                self.mouse-cursor = MouseCursor.col-resize;
                slider_hovered = true;
                if (event.kind == PointerEventKind.down) {
                    resizing = true;
                }
            }
        }
        moved => {
            if (resizing) {
                split = 100% - ((parent.width - self.mouse-x) / parent.width);
                split = max(split, 12%);
                split = min(split, 97%);
            }
        }
    }

    Rectangle {
        background: Palette.background;
        width: parent.width * split;
        x: 0px;
        min-height: 16px; /* @lsp:ignore-node */
            Sidebar {
            total_width: parent.width;
            total_height: parent.height;
            settings_button_clicked => {
                settings_shown = true;
                settings_button_clicked();
            }
            lif_files: lif_files;
            regen_table => {
                selected_lif_file = self.selected_lif_file;
                main_section.inner_tab_index = 0;
                table_changed()
            }
            filter_text_changed(text) => {
                lif_file_filter = text;
                filter_changed()
            }
            genpdf_button_clicked => {
                main_section.inner_tab_index = 1;
                genpdf_button_clicked()
            }
            print_button_clicked => {
                print_button_clicked()
            }
        }
    }

    Rectangle {
        background: Palette.background;
        width: parent.width * (100% - split);
        x: parent.width * split;
        min-height: 16px; /* @lsp:ignore-node */
            main_section := MainSection {
            total_width: parent.width;
            total_height: parent.height;
            event: event;
            race_event_present: race_event_set;
            table_data: table_data;
            table_changed => {
                root.table_changed()
            }
            pdf_images: pdf_images;
            new_pdf_image_width(new_width) => {
                pdf_image_width = new_width;
            }
            inner_tab_index: tab_index;
        }
    }

    // Slider
    slider_rect := Rectangle {
        width: 2px;
        x: parent.width * split;
        background: slider_hovered ? Palette.selection-background : Palette.control-background;
    }

    if (settings_shown): SettingsMenu {
        width: 80%;
        height: 80%;

        settings_data: settings_data;

        settings_add_path => {
            settings_add_path()
        }
        settings_edit_path(x, y) => {
            settings_edit_path(x, y);
        }
        settings_remove_path(i) => {
            settings_remove_path(i);
        }
        settings_update => {
            general_settings_update(self.settings_data)
        }
        close_button_click => {
            settings_shown = false;
            settings_close_button_clicked();
        }
    }
}
