import { Button, Palette } from "std-widgets.slint";
import { Sidebar } from "sidebar.slint";
import { SlintRaceEvent } from "structs.slint";
import { MainSection } from "mainsection.slint";

export component MainWindow inherits Window {
    width: 800px;
    height: 600px;
    property <float> split: 20%;
    property <bool> slider_hovered: false;

    out property <int> selected_lif_file: -1;

    in property <bool> race_event_set: false;
    in property <SlintRaceEvent> input_event;

    // Slider touch area
    TouchArea {
        width: parent.width;
        height: parent.height;
        pointer-event(event) => {
            if (abs(self.mouse-x - (parent.width * split)) <= 4px) {
                slider_hovered = false;
                self.mouse-cursor = MouseCursor.col-resize;
            } else {
                slider_hovered = true;
                self.mouse-cursor = MouseCursor.default;
            }
        }
        moved => {
            if (slider_hovered) {
                split = 100% - ((parent.width - self.mouse-x) / parent.width);
                split = max(split, 5%);
                split = min(split, 95%);
            }
        }
    }

    HorizontalLayout {
        Rectangle {
            background: Palette.background;
            width: parent.width * split;
            min-height: 16px; /* @lsp:ignore-node */
            Sidebar {
                total_width: parent.width;
                total_height: parent.height;
                selected_lif_file: selected_lif_file;
            }
        }

        Rectangle {
            background: Palette.background;
            width: parent.width * (100% - split);
            min-height: 16px; /* @lsp:ignore-node */
            MainSection {
                total_width: parent.width;
                total_height: parent.height;
                race_event: input_event;
                race_event_present: race_event_set;
            }
        }
    }

    // Slider
    slider_rect := Rectangle {
        width: 2px;
        x: parent.width * split;
        background: slider_hovered ? Palette.control-background : Palette.selection-background;
    }
}
