import { SlintEventRow } from "structs.slint";
import {
    TabWidget,
    StandardTableView,
    ScrollView,
    VerticalBox,
} from "std-widgets.slint";

export component MainSection {
    in property <bool> race_event_present;
    in property <SlintEventRow> event;
    in property <[[StandardListViewItem]]> table_data;
    in property <length> total_width: 100px;
    in property <length> total_height: 100px;

    in property <int> inner_tab_index;
    changed inner_tab_index => {
        tabs.current-index = inner_tab_index;
    }

    in property <[image]> pdf_images;
    callback new_pdf_image_width(float);

    out property <int> table_sort_index: -1;
    out property <bool> table_sort_ascending: true;
    callback table_changed();

    tabs := TabWidget {
        width: total_width;
        height: total_height;

        current-index: 0;

        Tab {
            title: "Raw Data";
            if (race_event_present): VerticalLayout {
                width: parent.width;
                height: parent.height;
                Text {
                    text: event.event-name + "\n" + event.event-code + " | " + event.start-time;
                    font-size: 24pt;
                    x: parent.width * 0.01;
                }

                StandardTableView {
                    sort-ascending(index) => {
                        root.table_sort_index = index;
                        root.table_sort_ascending = true;
                        root.table_changed();
                    }

                    sort-descending(index) => {
                        root.table_sort_index = index;
                        root.table_sort_ascending = false;
                        root.table_changed();
                    }
                    columns: [
                        { title: "Place" },
                        { title: "ID" },
                        { title: "Lane" },
                        { title: "First Name" },
                        { title: "Last Name" },
                        { title: "Club" },
                        { title: "Time" },
                    ];
                    rows: table_data;
                    init => {
                        table_changed();
                    }
                }
            }
        }

        Tab {
            title: "PDF";
            Rectangle {
                width: parent.width;
                ScrollView {
                    viewport-height: parent.height > parent.width ? parent.height * 2 : parent.width * 3;

                    changed width => {
                        new_pdf_image_width(self.width / 1px);
                    }

                    content := Rectangle {
                        for i in pdf_images.length: Image {
                            property <image> image: pdf_images[i];
                            source: image;
                            width: parent.width * 0.9;
                            y: i * (self.height + 10px);
                        }
                    }
                }
            }
        }

        init => {
            new_pdf_image_width(self.width / 1px);
        }
        changed width => {
            new_pdf_image_width(self.width / 1px);
        }
    }
}
