import { Button, ListView, Palette, LineEdit } from "std-widgets.slint";

export component Sidebar {
    in-out property <[string]> lif_files;
    in property <length> total_width: 100px;
    in property <length> total_height: 100px;
    in-out property <int> selected_lif_file: -1;

    callback settings_button_clicked();
    callback regen_table();
    callback filter_text_changed(string);
    callback genpdf_button_clicked();
    callback print_button_clicked();

    VerticalLayout {
        spacing: 3px;
        height: total_height;
        alignment: LayoutAlignment.start;
        padding-left: total_width * 0.2;
        padding-right: total_width * 0.2;

        Text {
            text: "Controls";
        }

        Button {
            text: "Select Most Recent";
            clicked => {
                selected_lif_file = 0;
                regen_table();
            }
        }

        genpdf_button := Button {
            text: "Generate PDF";
            clicked => {
                genpdf_button_clicked()
            }
        }

        print_button := Button {
            text: "Print";
            clicked => {
                print_button_clicked()
            }
        }

        settings_button := Button {
            text: "Settings";
            clicked => {
                settings_button_clicked()
            }
        }

        Text { }

        padding: 4px;
        Text {
            text: "Select Lif File";
        }

        LineEdit {
            placeholder-text: "Filter Races";
            edited(text) => {
                filter_text_changed(text);
            }
        }

        ListView {
            height: 70%;
            for i in lif_files.length: TouchArea {
                property <string> lif_file: lif_files[i];
                Rectangle {
                    background: i == selected_lif_file ? Palette.selection-background : Palette.alternate-background;
                    border-radius: 2px;
                }

                Text {
                    text: lif_file;
                    color: i == selected_lif_file ? Palette.selection-foreground : Palette.foreground;
                }

                clicked => {
                    selected_lif_file = i;
                    regen_table();
                }
            }
        }
    }
}
